#!/usr/bin/env python3
"""Generate the DRY-RUN MANIFEST (criterion e) — written BEFORE any mutation.

manifest.md contains:
1. The exact gh/GraphQL operations that will run (verbatim query shapes,
   placeholders resolved; node IDs referenced as runtime-resolved variables
   whose values live ONLY in /tmp/orchestraitor-board-cache/ — never here).
2. The expected item/edge manifest: every epic, task, gap issue, edge,
   label, and field value that will exist after the run.
"""

import hashlib
import json

import backlog_data as B

CACHE_DIR = "/tmp/orchestraitor-board-cache"

MUTATIONS_DOC = """## 0. Runtime-resolved variables (values live OUTSIDE the repo)

All node IDs are resolved at runtime via the queries below and cached in
`/tmp/orchestraitor-board-cache/` (never committed; the committed manifest
references them by variable name only).

| Variable | Resolves | Query |
|---|---|---|
| `$ORG_ID` | org `arbsec` node id | `organization(login: "arbsec") { id }` |
| `$PROJECT_ID` | project 1 "Arbsec Development" | `organization(login: "arbsec") { projectV2(number: 1) { id } }` |
| `$FIELD_STATUS` … | single-select field + option ids | `node(id: $PROJECT_ID) { ... on ProjectV2 { fields(first: 50) { ... on ProjectV2SingleSelectField { id name options { id name } } } } }` |
| `$FIELD_ESTIMATE` | number field id | same fields query (`dataType: NUMBER`) |
| `$TYPE_TASK_ID`, `$TYPE_EPIC_ID` | org issue-type ids | `organization(login: "arbsec") { issueTypes(first: 100) { nodes { id name } } }` |

Field/option names used (from `.agents/project/github-project.example.toml`,
verified live): Status = Triage/Backlog/Ready/In Progress/In Review/Done;
Target = MVP/Next/Later/Icebox; Risk = Low/Medium/High/Critical;
Priority = P0/P1/P2/P3; Estimate = number.

## 1. Prerequisite: Epic issue type — BLOCKED (recorded deviation, fallback applied)

The org `arbsec` has NO `Epic` issue type today (only Task/Bug/Feature —
verified via `organization(login: "arbsec") { issueTypes }`). Creating it
via `createIssueType` requires the `admin:org` (or `user`) OAuth scope; the
owner's token has only `gist, project, read:org, repo, workflow`, and scope
elevation requires an interactive browser flow the executor must not
attempt. Open org issue arbsec/orchestraitor#252 already requests
configuring org types "Task/Bug/Epic/Feature/Spike per
github-project.example.toml".

**Fallback (applied):** epics are created with the existing `epic` label —
the board's documented current type dimension (#252: "the Type dimension
lives in labels today") — and no native type. Leaf Tasks use the native
`Task` type (it exists). Remediation is one command per epic once the owner
creates the Epic type (see `set-epic-types.sh`, generated by apply.py from
the created issue numbers):

```sh
gh auth refresh -s admin:org   # owner, one time
gh api graphql -f query='mutation($o: ID!) { createIssueType(input:
  {ownerId: $o, name: "Epic", isEnabled: true, color: PURPLE}) { issueType { id } } }' -f o=<ORG_ID>
bash set-epic-types.sh        # gh issue edit <num> --add-type Epic (x12)
```

Also: repo `arbsec/orchestraitor` lacks the `needs-human-review` label
(documented board label; required on Critical guard tasks). Created via
`gh label create needs-human-review --repo arbsec/orchestraitor --color d73a4a
--description "security-sensitive; requires human sign-off"`.

## 2. Gap issues in arbsec/arbitraitor (created FIRST; tasks link to them)

Per issue (2 total), following arbitraitor's feature_proposal.yml template
(Problem / Proposed solution / Alternatives considered):

```sh
gh issue create --repo arbsec/arbitraitor \\
  --title "<title>" --body-file "<body>" \\
  --label enhancement [--label security-sensitive]
```

## 3. Epics (12) — issues in arbsec/orchestraitor

Per epic: create the issue with the `epic` label (native Epic type BLOCKED —
see §1), add to project, set fields.

```sh
gh issue create --repo arbsec/orchestraitor \\
  --title "<title>" --body-file "<body>" --label epic
```

(`addProjectV2ItemById` then adds the issue to the project. Once the org
Epic type exists, `set-epic-types.sh` applies `--add-type Epic` to all 12.)

Then per epic, 4 field writes via GraphQL (one call each):

```graphql
mutation setField($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
  updateProjectV2ItemFieldValue(input: {
    projectId: $projectId
    itemId: $itemId
    fieldId: $fieldId
    value: $value
  }) { projectV2Item { id } }
}
```

- Status  <- Backlog   (single-select option id from cache)
- Target  <- MVP | Icebox
- Priority<- P0 | P1 | P2 | P3
- Risk    <- Low | Medium | High | Critical

## 4. Leaf Tasks (72) — native sub-issues under their epic

Per task: create with type Task + parent + project + labels, then 5 field
writes (Status, Target, Priority, Risk, Estimate).

```sh
gh issue create --repo arbsec/orchestraitor \\
  --title "<title>" --body-file "<body>" --type Task \\
  --parent <epic-issue-number> \\
  [--label needs-human-review] [--label blocked:arbitraitor] \\
  [--label MVP]
```

(`MVP` is the board's documented proxy label for Target=MVP — the existing
ready-queue tooling filters on it; the Target field is set natively too.)

Field writes (same `updateProjectV2ItemFieldValue` mutation as epics):

- Status   <- Ready | Backlog   (gap-linked + ICE at Backlog)
- Target   <- MVP | Icebox
- Priority <- P0 | P1 | P2 | P3  (inherits epic)
- Risk     <- Low | Medium | High | Critical
- Estimate <- <number>            (ProjectV2FieldNumberValue)

## 5. Dependency edges (native blockedBy)

Epic-level wave edges (10) and task-level edges (53) use the same mutation;
cross-repo edges (2) pass an arbitraitor issue node id as the blocker:

```graphql
mutation addBlockedBy($issueId: ID!, $blockingIssueId: ID!) {
  addBlockedBy(input: { issueId: $issueId, blockingIssueId: $blockingIssueId }) {
    issue { number }
    blockingIssue { number }
  }
}
```

Same-repo edges may also be set at creation time via
`gh issue create --blocked-by <num>`; the apply script uses the GraphQL
mutation uniformly so every edge is logged identically.

## 6. Rate-limit discipline

Mutations run sequentially with a small pause between calls; every call's
duration and result is logged to `mutation-log.jsonl` (node IDs redacted in
the committed copy; raw log stays in the cache dir). A failed call stops the
run — the manifest + log make the exact succeeded set reconcilable.
"""


def main():
    lines = []
    a = lines.append
    a("# Dry-run manifest — orchestrator-first implementation backlog (plan todo 5)")
    a("")
    a("Written BEFORE any mutation (criterion e). Generated from `backlog_data.py`")
    a("(validated: 12 epics, 72 tasks, 63 edges, 2 gap issues).")
    a("")
    a("Board: org `arbsec`, project 1 \"Arbsec Development\" (shared with arbitraitor).")
    a("Auth: owner's gh auth (mekwall) — recorded D11 decision; items stay UNASSIGNED.")
    a("")
    a(MUTATIONS_DOC)

    # ---- expected item manifest ----
    a("")
    a("---")
    a("")
    a("## Expected item manifest")
    a("")
    a("### Gap issues (arbsec/arbitraitor)")
    a("")
    a("| id | title | labels |")
    a("|---|---|---|")
    for g in B.GAP_ISSUES:
        a(f"| {g['id']} | {g['title']} | {', '.join(g['labels'])} |")
    a("")
    a("### Epics (arbsec/orchestraitor, type Epic, Status=Backlog)")
    a("")
    a("| key | title | Priority | Target | Risk |")
    a("|---|---|---|---|---|")
    for e in B.EPICS:
        a(f"| {e['key']} | {e['title']} | {e['priority']} | {e['target']} | {e['risk']} |")
    a("")
    a("### Leaf Tasks (type Task, native sub-issues)")
    a("")
    a("| id | epic | title | Status | Target | Priority | Risk | Estimate | labels |")
    a("|---|---|---|---|---|---|---|---|---|")
    for t in B.TASKS:
        d = B.task_defaults(t)
        labels = ", ".join(d.get("labels", [])) or "-"
        a(
            f"| {d['id']} | {d['epic']} | {d['title']} | {d['status']} | "
            f"{d['target']} | {d['priority']} | {d['risk']} | {d['estimate']} | {labels} |"
        )
    a("")
    a("### Dependency edges (native blockedBy: blocked <- blocker)")
    a("")
    a("**Epic-level wave edges (10):**")
    a("")
    a("| blocked epic | blocked by epic |")
    a("|---|---|")
    for blocked, blocker in B.EPIC_EDGES:
        a(f"| {blocked} | {blocker} |")
    a("")
    a("**Task-level edges (intra-epic chains + cross-epic bootstrap edges):**")
    a("")
    a("| blocked task | blocked by |")
    a("|---|---|")
    n_task_edges = 0
    for blocked, blocker in B.all_task_edges():
        a(f"| {blocked} | {blocker} |")
        n_task_edges += 1
    a("")
    a(f"Total edges: {len(B.EPIC_EDGES)} epic-level + {n_task_edges} task-level "
      f"(of which 2 are cross-repo to arbsec/arbitraitor gap issues).")
    a("")
    a("### Postconditions (what the read-back must assert)")
    a("")
    a("1. 12 epic issues on the board (native Epic type BLOCKED — `epic` label fallback, see §1):")
    a("   E0=P0, E9=P2, E1-E8+E10=P1, ICE=P3;")
    a("   E0-E10 Target=MVP, ICE Target=Icebox; every epic >= 1 leaf Task.")
    a("2. Every Task body non-empty with >= 1 `docs/spec/` anchor + acceptance-criteria + QA sections.")
    a("3. Fields: Target=MVP + Status=Ready for non-gap tasks; gap-linked (E5-T7, E5-T8)")
    a("   and ICE-T1 at Backlog; Risk as specified (E5 all-Critical, E8 guard tasks Critical,")
    a("   arb-gap-linked Critical, all with needs-human-review label).")
    a("4. E0 task bodies carry thin-slice markers naming the deepening epic.")
    a("5. Edges resolve via the native dependencies API: E1->E3, E7->E8 (epic level);")
    a("   E5-T7/E5-T8 -> the two arbsec/arbitraitor issues (cross-repo).")
    a("6. Both arbitraitor gap issues exist (`gh issue view`); Orchestraitor tasks link them")
    a("   + carry `blocked:arbitraitor`.")
    a("")
    a("### Body digests (integrity: created bodies must match this manifest)")
    a("")
    a("| item | sha256(body)[:16] |")
    a("|---|---|")
    for e in B.EPICS:
        h = hashlib.sha256(e["body"].encode()).hexdigest()[:16]
        a(f"| {e['key']} | {h} |")
    for t in B.TASKS:
        h = hashlib.sha256(t["body"].encode()).hexdigest()[:16]
        a(f"| {t['id']} | {h} |")
    for g in B.GAP_ISSUES:
        h = hashlib.sha256(g["body"].encode()).hexdigest()[:16]
        a(f"| {g['id']} | {h} |")

    out = "\n".join(lines) + "\n"
    with open("manifest.md", "w", encoding="utf-8") as f:
        f.write(out)
    # machine-readable companion for verify.py
    with open("manifest.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "epics": [
                    {"key": e["key"], "title": e["title"], "priority": e["priority"],
                     "target": e["target"], "risk": e["risk"]}
                    for e in B.EPICS
                ],
                "tasks": [
                    {**B.task_defaults(t),
                     "body_sha256": hashlib.sha256(t["body"].encode()).hexdigest()}
                    for t in B.TASKS
                ],
                "epic_edges": B.EPIC_EDGES,
                "task_edges": sorted(B.all_task_edges()),
                "gaps": [{"id": g["id"], "title": g["title"], "repo": g["repo"],
                          "labels": g["labels"]} for g in B.GAP_ISSUES],
            },
            f,
            indent=1,
        )
    print(f"manifest.md + manifest.json written ({len(out)} bytes, "
          f"{len(B.EPICS)} epics, {len(B.TASKS)} tasks)")


if __name__ == "__main__":
    main()
